### ISSUE TITLE
[Bug] Accuracy from Model.evaluate() is inconsistent with manually computed accuracy

### ISSUE THREAD

**Issue by alexander-g** [poets-ai/elegy#109]
**Describe the bug**
The accuracy reported by `Model.fit()` or `Model.evaluate()` is different from manually computed via `model.predict(x).argmax(-1) == y).mean()`

**Minimal code to reproduce**
[Colab Notebook](https://colab.research.google.com/drive/1KNI71b83K-GyGDePEUjG5E8mNO51DxCM?usp=sharing)

**Expected behavior**
Both should be the same.

**Library Info**
Latest commit in master 19ec87ba85e9e5331a77e19ecdddadf2c37161fc

**Comment by cgarciae** [comment]
@alexander-g thanks for reporting!

I will add this as a test case once its solved.

**Comment by cgarciae** [comment]
The problem was that it wasn't getting the initial state for the metrics correct so it was getting the wrong numbers after accumulation.

This is fixed in #110 which should be merge after #108.
