### ISSUE TITLE
Discussion: What shall we name the "low-level" API feature?

### ISSUE THREAD

**Issue by cgarciae** [poets-ai/elegy#150]
#139 Introduces a feature called "low-level API" which is the Pytorch Lightning-like API feature but I don't like that is sounds a bit obscure.

Potential options:
* Low Level API (current)
* Framework Agnostic API
* ???

Open to suggestions.

**Comment by Davidnet** [comment]
Since elegy is a lament for the dead, maybe we can call the low level API -inferno API-? In all seriousness, agnostic API?

**Comment by 8bitmp3** [comment]
`melody` ? I checked the formal definition of "elogy" and it mentioned "melody" 🎶

**Comment by 8bitmp3** [comment]
> In all seriousness, agnostic API?

@Davidnet @cgarciae IMO, referring to it as "low-level" is probably more intuitive for new folks, since `elegy` supports `haiku`, `optax` and `flax` (some users may need to get used to what these library-frameworks mean and what they can do.)
