### ISSUE TITLE
[Bug] Low-level API Flax example is misleading.

### ISSUE THREAD

**Issue by lkhphuc** [poets-ai/elegy#195]
**Describe the bug**
An elegy model that was passed in a `flax.linen.module.Module`, e.g. `eg.Model(module=FlaxLinenModule)`, internally wrap it intto a `eg.FlaxModule`. 

So in the example in the README, quoted below, Flax's Module method cannot be accessed via `self.module`.

After digging around the source code, I have learn to use `self.module` as a eg.FlaxModule, like
```
self.module.init_rngs = ('params', 'my_stochasitic_ops')
self.module.rngs = ('dropout', 'my_stochasitic_ops')
```

**Minimal code to reproduce**
Small snippet that contains a minimal amount of code.
```python
class LinearClassifier(eg.Model):
    params: Mapping[str, Any] = eg.Parameter.node()
    batch_stats: Mapping[str, Any] = eg.BatchStat.node()
    next_key: eg.KeySeq

    def init_step(self, key, inputs):
        self.next_key = eg.KeySeq(key)

       # self.module is converted to eg.FlaxModule
       # Could use a different name when init to retain linen module
        _, variables = self.module.init_with_output(
            {"params": self.next_key(), "dropout": self.next_key()}, x
        )
        self.params = variables["params"]
        self.batch_stats = variables["batch_stats"]

        self.optimizer = self.optimizer.init(self.parameters())

    def test_step(self, inputs, labels):
        # forward
        variables = dict(
            params=self.params,
            batch_stats=self.batch_stats,
        )
        logits, variables = self.module.apply(
            variables,
            inputs, 
            rngs={"dropout": self.next_key()}, 
            mutable=True,
        )
        self.batch_stats = variables["batch_stats"]
        
        # loss
        target = jax.nn.one_hot(labels["target"], 10)
        loss = optax.softmax_cross_entropy(logits, target).mean()

        # logs
        logs = dict(
            accuracy=accuracy,
            loss=loss,
        )
        return loss, logs, self
```

**Expected behavior**
The example can be fixed easily by assigning the flax module to a different variable not coopted by elegy like: self.flax_module.

Since this is a new release without documentation, I wasn't sure if working directly with Flax is expected or we should use `eg.FlaxModule` instead.

**Comment by cgarciae** [comment]
Nice catch @lkhphuc! 100% correct.
I'll fix the example by adding an `__init__` method an assigning `module` to `self.flax_module`.

**Comment by lkhphuc** [comment]
Thank, looking forward to the docs. Happy to help with that as well where I can.

**Comment by cgarciae** [comment]
@lkhphuc I am planning the first community event to help people that want to start contributing, stay tuned!
