### ISSUE TITLE
Pure functions in Elegy ?

### ISSUE THREAD

**Issue by pablo2909** [poets-ai/elegy#229]
Hi,

I have stumbled upon elegy last week and I wanted first to thank you for this great work! I have been able to learn a lot by reading the code!

I come from the PyTorch environment and have started learning Jax a couple of weeks ago. In PyTorch I implemented a very simple module where we could define Callbacks (inspired by fastai course), which made training a model very modular and easy to modify. I wanted to do something similar in Jax, but have been struggling since Jax requires pure functions to leverage JIT, vmap, pmap etc.

What I want to do is:

_Implement a module that can train a model through a list of callbacks, while respecting Jax's pure functions philosophy in order to leverage JIT_

My question is thus:
- Is elegy a module that provides a solution to the problem above ?

Thanks a lot for taking the time and for providing Elegy to the community 
Kindest regards

**Comment by lkhphuc** [comment]
Hi, the documentation is a bit lacking atm but Elegy does have support for callbacks. You can check some examples in the `elegy/callbacks` folder and pass them in the fit method, e.g `model.fit(..., callbacks=[Tensorboard(logdir), Wandb()])`

> Implement a module that can train a model through a list of callbacks, while respecting Jax's pure functions philosophy in order to leverage JIT

I'm not sure what are the callbacks you have in mind, but usually Jax pure function philosophy doesn't get in the way callbacks.
The pure function aspect of training (for grad, jit) is handled in the low-level API (`pred_step`, `test_step`, `train_step`,...) and the callbacks usually are only to produce side effect (ideally it should be async if possible). 
But in the callbacks you have access to the full model at `self.model`, so I haven't tried this yet but I suppose you can perform some update to (some part of the) model in the callback and merge back to `self.model.merge(new_params)` etc.
If you try this out and see any error or rough edge feel free to open another issue. Hope this help.

**Comment by pablo2909** [comment]
Thank you for your answers.

If I understand well, it's functions from the low-level API(`pred_step`, `test_step`, `train_step`,...) that are pure functions right ? The rest is more standard Python code, which is acceptable as it won't be jitted ? 

Also, if I understand well, in `pred_step` for example, the trick you use to make it pure is to never update any state of `self`, but to output it from the function ? I believe there is a similar idea explain in JAX's doc.

Lastly on which functions in the API are we supposed to call `jit` ?

Again thank you for your time,

**Comment by cgarciae** [comment]
@pablo2909 Yes, `train_step` and friends are pure functions which is why they return self (or equivalent) to propagate the state. Those functions however are managed by the distribution strategies which actually `jit` or `pmap` them. 

I hope this become more clear in the future as per the proposal the JAX part would be an entirely separate object.

**Comment by pablo2909** [comment]
Thank you very much for the explanations, looking forward for the future then ! :)
