### ISSUE TITLE
[Bug] Importing elegy results in a deep-lying AttributeError

### ISSUE THREAD

**Issue by ericmjl** [poets-ai/elegy#233]
**Describe the bug**

When I try to import elegy:

```python
import elegy as eg
```

I get the following stack trace (hidden in the details tag):

<details>
<pre><code>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/ericmjl/github/incubator/score-models/notebooks/0[1]()-score-function.ipynb Cell 30' in <module>
----> 1[ import elegy as eg

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/elegy/__init__.py:5, in <module>
      ]()[1]()[ # isort:skip_file
      ]()[3]()[ __version__ = "0.8.6"
----> ]()[5]()[ from treex import *
      ]()[7]()[ import elegy.types as types
      ]()[8]()[ import elegy.utils as utils

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/treex/__init__.py:8, in <module>
      ]()[5]()[ from treeo import *
      ]()[7]()[ from treex.key_seq import KeySeq
----> ]()[8]()[ from treex.losses import Loss
      ]()[9]()[ from treex.metrics import LossAndLogs, Metric
     ]()[10]()[ from treex.module import (
     ]()[11]()[     Module,
     ]()[12]()[     ModuleMeta,
   (...)
     ]()[16]()[     rng_key,
     ]()[17]()[ )

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/treex/losses/__init__.py:2, in <module>
      ]()[1]()[ from .cosine_similarity import CosineSimilarity, cosine_similarity
----> ]()[2]()[ from .crossentropy import Crossentropy, crossentropy
      ]()[3]()[ from .huber import Huber, huber
      ]()[4]()[ from .loss import Loss, Reduction

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/treex/losses/crossentropy.py:5, in <module>
      ]()[3]()[ import jax
      ]()[4]()[ import jax.numpy as jnp
----> ]()[5]()[ import optax
      ]()[7]()[ from treex import types, utils
      ]()[8]()[ from treex.losses.loss import Loss, Reduction

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/optax/__init__.py:17, in <module>
      ]()[1]()[ # Copyright 2019 DeepMind Technologies Limited. All Rights Reserved.
      ]()[2]()[ #
      ]()[3]()[ # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     ]()[13]()[ # limitations under the License.
     ]()[14]()[ # ==============================================================================
     ]()[15]()[ """Optax: composable gradient processing and optimization, in JAX."""
---> ]()[17]()[ from optax import experimental
     ]()[18]()[ from optax._src.alias import adabelief
     ]()[19]()[ from optax._src.alias import adafactor

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/optax/experimental/__init__.py:20, in <module>
      ]()[1]()[ # Copyright 2021 DeepMind Technologies Limited. All Rights Reserved.
      ]()[2]()[ #
      ]()[3]()[ # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     ]()[13]()[ # limitations under the License.
     ]()[14]()[ # ==============================================================================
     ]()[15]()[ """Experimental features in Optax.
     ]()[16]()[ 
     ]()[17]()[ Features may be removed or modified at any time.
     ]()[18]()[ """
---> ]()[20]()[ from optax._src.experimental.complex_valued import split_real_and_imaginary
     ]()[21]()[ from optax._src.experimental.complex_valued import SplitRealAndImaginaryState

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/optax/_src/experimental/complex_valued.py:32, in <module>
     ]()[15]()[ """Complex-valued optimization.
     ]()[16]()[ 
     ]()[17]()[ When using `split_real_and_imaginary` to wrap an optimizer, we split the complex
   (...)
     ]()[27]()[ See details at https://github.com/deepmind/optax/issues/196
     ]()[28]()[ """
     ]()[30]()[ from typing import NamedTuple, Union
---> ]()[32]()[ import chex
     ]()[33]()[ import jax
     ]()[34]()[ import jax.numpy as jnp

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/chex/__init__.py:17, in <module>
      ]()[1]()[ # Copyright 2020 DeepMind Technologies Limited. All Rights Reserved.
      ]()[2]()[ #
      ]()[3]()[ # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     ]()[13]()[ # limitations under the License.
     ]()[14]()[ # ==============================================================================
     ]()[15]()[ """Chex: Testing made fun, in JAX!"""
---> ]()[17]()[ from chex._src.asserts import assert_axis_dimension
     ]()[18]()[ from chex._src.asserts import assert_axis_dimension_comparator
     ]()[19]()[ from chex._src.asserts import assert_axis_dimension_gt

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/chex/_src/asserts.py:26, in <module>
     ]()[23]()[ import unittest
     ]()[24]()[ from unittest import mock
---> ]()[26]()[ from chex._src import asserts_internal as _ai
     ]()[27]()[ from chex._src import pytypes
     ]()[28]()[ import jax

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/chex/_src/asserts_internal.py:32, in <module>
     ]()[29]()[ from typing import Any, Sequence, Union, Callable, Optional, Set, Tuple, Type
     ]()[31]()[ from absl import logging
---> ]()[32]()[ from chex._src import pytypes
     ]()[33]()[ import jax
     ]()[34]()[ import jax.numpy as jnp

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/chex/_src/pytypes.py:40, in <module>
     ]()[37]()[ PyTreeDef = type(jax.tree_structure(None))
     ]()[38]()[ Shape = Tuple[int, ...]
---> ]()[40]()[ CpuDevice = jax.lib.xla_extension.CpuDevice
     ]()[41]()[ GpuDevice = jax.lib.xla_extension.GpuDevice
     ]()[42]()[ TpuDevice = jax.lib.xla_extension.TpuDevice

AttributeError: module 'jaxlib.xla_extension' has no attribute 'CpuDevice']()
</code></pre>
</details>

**Minimal code to reproduce**
Small snippet that contains a minimal amount of code.
```python
import elegy
```

Seeing as this is deep-lying, I'm wondering if there is an issue with the underlying dependencies?

Following the stack trace, I have the following version numbers:

- elegy: 0.8.6
- chex: 0.1.2
- treex: 0.6.10
- optax: 0.1.2
- jax: 0.3.7
- jaxlib: 0.3.7+cuda11.cudnn82

**Comment by cgarciae** [comment]
Hey! This seems to be an incompatibility between `chex` and `jax` / `jaxlib` versions.

> File ~/anaconda/envs/score-models/lib/python3.9/site-packages/chex/_src/pytypes.py:40, in 
]()[37](https://github.com/poets-ai/elegy/issues/233)[ PyTreeDef = type(jax.tree_structure(None))
](https://github.com/poets-ai/elegy/issues/233)[38](https://github.com/poets-ai/elegy/issues/233)[ Shape = Tuple[int, ...]
---> ](https://github.com/poets-ai/elegy/issues/233)[40](https://github.com/poets-ai/elegy/issues/233)[ CpuDevice = jax.lib.xla_extension.CpuDevice
](https://github.com/poets-ai/elegy/issues/233)[41](https://github.com/poets-ai/elegy/issues/233)[ GpuDevice = jax.lib.xla_extension.GpuDevice
](https://github.com/poets-ai/elegy/issues/233)[42](https://github.com/poets-ai/elegy/issues/233)[ TpuDevice = jax.lib.xla_extension.TpuDevice
>
> AttributeError: module 'jaxlib.xla_extension' has no attribute 'CpuDevice']()

Try:

```bash
pip install -U chex jax jaxlib
```

**Comment by ericmjl** [comment]
Leaving a comment back here to confirm that I've fixed the bug by installing `chex` from source. That's the temporary fix until a new version of chex is released on PyPI.

**Comment by ericmjl** [comment]
Thank you for responding quickly on the issue, @cgarciae!
