### ISSUE TITLE
Implement Callback API

### ISSUE THREAD

**Issue by cgarciae** [poets-ai/elegy#4]
* Port Callback API from Keras
* Implement History structure
* Implement Metrics callback (maybe this isn't a full callback)

**Comment by cgarciae** [comment]
Tensorboard callback: 

https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/keras/callbacks.py#L1617-L2151

**Comment by cgarciae** [comment]
ProgressBar callback:

Option 1: https://www.tensorflow.org/addons/tutorials/tqdm_progress_bar
Option 2: Use keras progress bar

**Comment by charlielito** [comment]
> ProgressBar callback:
> 
> Option 1: https://www.tensorflow.org/addons/tutorials/tqdm_progress_bar
> Option 2: Use keras progress bar

Keras progress bar and Calllbacks impleted in https://github.com/poets-ai/elegy/pull/14 @sebasarango1180
