### ISSUE TITLE
Add how to build the docs instructions

### ISSUE THREAD

**Issue by srcolinas** [poets-ai/elegy#49]
For new contributors it may be helpful to have instructions on building docs, this way one can try something before making the PR. If this does not sound like the expected workflow, we need such description to beware of the workflow.

**Comment by cgarciae** [comment]
Hey @srcolinas, that is a great idea! We should add it to the README. The easiest way to setup the project for development is to run 
```
poetry install
```bash
We use `mkdocs` for the documentation, you can start the local server by running
```bash
mkdocs serve
```
